### ISSUE TITLE
MS0108: Visualizer functions

### ISSUE THREAD

**Issue by idhamari** [VisSimKoblenz/opensimQt#10]
In this issue, we integrate the visualizer with the navigator. These tasks can be done in any order, the future work is not important for now :

* [x] Rename the other visualizer tabs:
     - We can use the other tabs for other things, we should be able to display and hide the tab as needed(if this not possible, we just display nothing):
         - Browser for the help menu to display web pages. 
         - Display the tools
         - Display the plotting 
         - Display the scaling tool 

          
    
* [x] connection between the navigator and the visualizer. 
       - implement the table properties of the model components. 
       - the connection should be two-ways. 
* [x] a very small toolbar for the visualizer window with the functions related to the view. 
       - the ones in the java gui in the top left. this can be done similar to [this example](https://lorensen.github.io/VTKExamples/site/Cxx/Widgets/TexturedButtonWidget/).
* [ ] add the coordinates tab.
       - it should interact with the visualizer and the model file.       
       - Future work: use a transformation menu similar to the one from Slicer. 
* [x] add ground floor. 
* [ ] use background image as skybox    
* [ ] Navigator element popup menus. 
* [ ] Future work: the visualizer window can be a full screen.

**Comment by idhamari** [comment]
@yasseerr  
I found this interesting [example](https://lorensen.github.io/VTKExamples/site/Cxx/Widgets/TexturedButtonWidget/)

I think we can use similar idea to implement the buttons in the top left of the visualizer in the java interface. We can even use cooler 3D buttons. What do you think?

**Comment by idhamari** [comment]
@yasseerr just checked, it seems vtk 9 will be released soon and 8.2 is stable. Please use 8.2.0. This will help to implement the skybox and other missing features.

![Screenshot from 2020-03-09 18-37-03](https://user-images.githubusercontent.com/28802516/76241454-4a721280-6235-11ea-82a3-d12d928e767e.png).

**Comment by yasseerr** [comment]
we will try and implement those buttons using vtk and hope it wont affect the performance,
and for vtk i m already using the 8.20

**Comment by idhamari** [comment]
> and for vtk i m already using the 8.20

Excellent I just build it and the compilation works but I get this runtime error: 

     : error while loading shared libraries: libvtkFiltersExtraction-8.2.so.1: cannot open shared object file: No such file or directory

Any idea? if you don't I will check this tomorrow.

**Comment by idhamari** [comment]
The error above is fixed and everything now works. The problem was related to multiple Qt version installed. I removed all of them and reinstall qt using the terminal: 

           sudo apt install qtdeclarative5-dev --reinstall qttools5-dev libqt5x11extras5-dev  qtchooser qt5-default qtwebengine5-dev qtcreator libqt5charts5-dev libqt5opengl5-dev libqt5designercomponents5 libqt5gstreamer-dev libqt5multimedia5-plugins libqt5x11extras5-dev libqt5webview5-dev libqt5websockets5-dev libqt5webkit5-dev libqt5webenginewidgets5 libqt5webenginecore5 libqt5webchannel5-dev libqt5svg5-dev libqt5qml5 libqt5xmlpatterns5-dev libqt5xdg-dev

This installs Qt-5.9.5.

**Comment by idhamari** [comment]
@yasseerr 

Its been a week since the last commit. Please report here your progress or difficulties. 

I found someone for the python milestone so I hope we will get some progress soon.

**Comment by yasseerr** [comment]
@idhamari 
sorry for the delay duo to academic/home tasks i will return as soon as possible
for the progress i m currently  working on the properties widgets which have different sub widgets  for the functions/objects/... to edit the properties and need model on it own, and Qt does not have the sheet tool provided by java so a model was developed from the ground and this is the reason for the delay
for the python ready to help with integration when its needed to achieve more progress

**Comment by idhamari** [comment]
Well done! 

I think you should start with the visualization stuff first. For editing the properties, we have a workaround e.g edit the text in the model file.

**Comment by yasseerr** [comment]
Thank you! 
ok ,i will focus then on the visualization first , the properties can be displayed for now and the editing widgets and models for the properties will be implemented afterwards

**Comment by idhamari** [comment]
@yasseerr 

I have a problem viewing this model that has .obj :

[tst.zip](https://github.com/VisSimKoblenz/opensimQt/files/4480701/tst.zip)

The model appears correctly in the java interface but not in our opensimQt

Could you please check what is the problem? this is urgent as I am working on a similar model now.

**Comment by yasseerr** [comment]
@idhamari 
i just checked and it seems we were using vtkXMLPolyDataReader to read the vtp files which they where xml files but the .obj files are not XML files
so do you want to fix that first and create Obj files handlers , becuase i was working on adding the button widgets inside the vtk visualizer using the vtkTexturedButtonWidget and focusing on two issues loading the png images to the vtkImageData because the given exemple create the texture/image by code and the second issue i m working on is how to prevent vtkRenderWindowInteractor from stopping the qt Interface to intercept the clicks

**Comment by idhamari** [comment]
@yasseerr 

Thanks for the information. Our interface should support at least all types that are supported by the current java interface. 

I found a workaround so please continue what you are doing and go back to this as soon as you finished.

**Comment by yasseerr** [comment]
Hi! do you want to migrate to vtk 9.0 r2 release 17 days ago or keep using vtk 8.2 as the first fix some issues

**Comment by idhamari** [comment]
> as the first fix some issues

if vtk 9 is useful, please use it.

**Comment by yasseerr** [comment]
ok ! thanks  but a rebuild is needed when testing as some classes like QVTKOpenGLWidget became deperecated

**Comment by idhamari** [comment]
Ok, I will rebuild vtk to use vtk 9.0 r2

**Comment by idhamari** [comment]
@yasseerr 

I just checked the last update. Everything works and It looks excellent but there is a performance issue.

**Comment by yasseerr** [comment]
@idhamari 
yes the last version is so slow compared with the 8.2 i m currently rebuilding to debug mode and trying to find the problem so we can implement the skybox+textured ground

**Comment by yasseerr** [comment]
@idhamari
i was using --debug if you are building vtk with debug and not debbuging the code switch to DebWithReleaseInfo and it will be fast

**Comment by idhamari** [comment]
@yasseerr  I am already using release build in Ubuntu. I will test it next week on Windows and see if there is difference.

 For now please try to complete this task before the end of this month. If there is something takes long time, please create a new issue describing the problem so I can add a solution or a workaround.

**Comment by yasseerr** [comment]
@idhamari 
ok! it should be working smouthly in wondow 
and i will try to finish before the end of the month but some vtk bugs toke some time maybe with vtk 9 it will be straight forward, 
>for the rename other visualizer-tabs what does it says exacly

**Comment by idhamari** [comment]
> but some vtk bugs toke some time 

That is why we should open new issues for them.

> for the rename other visualizer-tabs what does it says exactly

The idea is to have them hidden (with no title) for now and display them when needed. The programming names can be something like vsVWTab1 vsVWTab2 ...etc 
short for vsVisualizerWindowTab

**Comment by yasseerr** [comment]
ok! you can add and remove tabs from the QTabView programatically at any time but what is their content, 
do they start empty or they represent the OpenGL and Three.js tabs

**Comment by idhamari** [comment]
Then leave them for now. When we need them, we use them.

**Comment by yasseerr** [comment]
alright so i will remove them from the view and add them at any time during the execution , lets say when you click a button

**Comment by idhamari** [comment]
Next ToDOs:

* [x] fix reload
  - the visualizer objects e.g. small buttons, ground, skybox.  should always be there
 - model objects can be removed, modified or added.  
* [x] supports other model geometry e.g stl, obj ..etc
      - there are different readers in vtk e.g 
      -  create a general reader class. vsMeshReader(meshFilename) and it return the correct reader
      - for now it should supports vtp, obj, stl and vtk
* [x] supports other model geometry e.g stl, obj ..etc
* [x] select model object in visualizer should change its color to e.g. orange, then clicking again, it is unselected.
* [x] an icon for the ground to make visible or in-visible

**Comment by idhamari** [comment]
Only two more tasks and we close this issue.

**Comment by yasseerr** [comment]
@idhamari 
hi! before closing just for the rename in the popup menu
you are willing use xml instead of openSimObject Properties (saving the model to the file) right?
if so what library do you prefer OpenSim::Xml , TinyXml , Qt xml

**Comment by idhamari** [comment]
@yasseerr 

> you are willing use xml instead of openSimObject Properties (saving the model to the file) right?

I prefer OpenSim::Xml, this gives us more understanding of how opensim works. If this is difficult, then let's use Qt.

**Comment by yasseerr** [comment]
ok then a class vsXmlModelUtil will be created to handle xml operations

**Comment by yasseerr** [comment]
@idhamari 
the rename(model,body, from xml)/hide/show actions are added and mereged with master, give them a look and  is there any priority task before switching to simulation

**Comment by idhamari** [comment]
@yasseerr 

I just test it and everything works, thanks for your effort. Please start working on the next milestone when you have time.
