### ISSUE TITLE
MS0302: implement plugins function

### ISSUE THREAD

**Issue by idhamari** [VisSimKoblenz/opensimQt#15]
This probably the most challenging task in this milestone. We need a simple way to integrate a new simulation element. What the java interface does is loading a library. We can do the same by calling 

       opensim-cmd -L libraryfile.dll  xmlfile

This should work similarly to the previous tasks. 

* [ ] calling opensim-cmd with libraries from a folder.
    - the new model elements should be added to a model elements database and the navigator. 
    - when running the simulation, it should use the libraries and the new elements. 

The new idea is to create the element using a python script. The python script should replace loading the library. Probably we should do this in the python scripting milestone as we may need to implement a python version of OpenSim. This means all opensim-core and simbody files should have a python version. Shall we make a new project for this?

**Comment by idhamari** [comment]
For now, I think this should be handled similar to the java interface. We need to know: 

* [ ] how the force properties are loaded to the navigator
* [ ] how the force modified properties are used in the simulation.

**Comment by idhamari** [comment]
@yasseerr this is your next task. If needed, we can have an online meeting to explain it. The plugin is a customized opensim object e.g. force represented by a library e,g, .dll or .so. Usually, it is added manually to the .osim file e.g. by text editor but in the example, I wrote a simple function that opens the .osim file and adds the plugin object (maybe we can add it to our model class). The library is loaded from a pre-defined path in opensim and after that, the model can be loaded and recognize the object. In the java interface, one can modify the force and do the simulation using the new modified values. Please experiment with the attached example. 
  
Here are more resources:

https://simtk-confluence.stanford.edu:8443/display/OpenSim/Using+Plugins

Here is an example you can build and use [pendulumWithPlugin.zip](https://github.com/VisSimKoblenz/opensimQt/files/4914969/pendulumWithPlugin.zip).

This is the only task in your current milestone, other tasks will be added later to a new milestone.

**Comment by yasseerr** [comment]
@idhamari 
well understood , i will check how the integration happend  and the techniques in the exemple and opensim gui and try to come up with a solution to plug the dlls to OpenSimQt using the QtPlugin system and go from there .if any advancement i will report back and if there is something missing or unclear i will contact you for a meeting

also i will be pushing on the navigator branch as this is not linked to simulation i think

**Comment by yasseerr** [comment]
Hi @idhamari 
i think i found a way to connect the plugins to qt, but what opensim version are you using for the pendulum plugin because i cant build it with cmake using the current openSim installation and i read that the plugin and the OpenSim should use the same version .or if you have other exemples 

UPDATE: it was a cmake cache from a wrong build

**Comment by yasseerr** [comment]
@idhamari hi again! 
where do you copy the libraries to, in the OpenSimGUI because i tried multiple folderes still have no entry on the User Plugins menu

**Comment by idhamari** [comment]
Hi @yasseerr, 

> where do you copy the libraries to, in the OpenSimGUI because i tried multiple folderes still have no entry on the User Plugins menu

Good question, for me the path was not stable, I think it is related where netbeans and opensim at the same time. It was not clear to the point I have to create different folders and copy the libraries to all of them. I ended up creating a dialog to show the folder path when opensim starts. Currently it is in opensim-gui/Gui/opensim/plugins

You can find this in ToolsLoadUserLibraryAction.java 

This is the part of the code I used:

    public JMenuItem getMenuPresenter() {
      JMenu displayMenu = new JMenu("VisSim User Plugins");
      final boolean windows = System.getProperty("os.name").toLowerCase().contains("win");
      FileFilter fileFilter = new FileFilter() {
                public boolean accept(File file) {
                    // For now .dll for windows should generalize to other platforms based on OS property
                    String dynamicLibraryExtension = (windows)?".dll":".so";
                    return (!file.isDirectory()&& file.getName().endsWith(dynamicLibraryExtension));
                }
      };      
      File rootExtensionsDirectory= new File("plugins");
      String fullPath = rootExtensionsDirectory.getAbsolutePath();
      JOptionPane.showMessageDialog(null,"PluginPath:"+fullPath, "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
      System.out.println("Loading plugins from directory "+fullPath);
      File[] files = rootExtensionsDirectory.listFiles(fileFilter);
      if (files == null)  return displayMenu;
      
      for (int i=0; i<files.length; i++){

**Comment by yasseerr** [comment]
@idhamari 
Thnx for helping . now i have the dragForce and dragForce2 in other forces it was as you said in opensim-gui/Gui/opensim/plugins

**Comment by yasseerr** [comment]
Hi @idhamari 
loading the plugin functionality is now implemented as in this video [LINK](https://drive.google.com/file/d/1Mof93UOQJq5mGhwwhJgINMGOVIFcmRro/view?usp=sharing) , after building the plugin you can import it to OpenSimQt by:
- place it in the plugins folder inside the build folder
- click import new plugin action from the tool menu and select the library (extention depend on the OS ,tested on windows) file from folder and it will be automaticaly placed.

when importing a new library the you can deside to always load it on startup
the onStartup libraries can be found in the config.ini file

in the above video you can see that the forces nodes are added to the navigator and have effect in the simulation
the changes are in the navigator-features branche if you want to test befor merging

**Comment by idhamari** [comment]
Well done @yasseerr  :watermelon: I just tested, it says the library is loaded  but there is no drag force in the navigator and the simulation is not using the force. I will do more testing and report here.

![Screenshot from 2020-07-19 18-30-26](https://user-images.githubusercontent.com/28802516/87879958-382b9080-c9ee-11ea-95e2-a73e712bb61f.png)

**Comment by idhamari** [comment]
@yasseerr 

this is what happens when I click Tools\User plugins then I clicke on  libBodyDragForce.so: 

* I get a dialog that says: library libBodyDragForce.so has been loaded successfully 
* In the console :

                 pluging is loading  "libBodyDragForce.so"
                 dlerror: /home/ibr/myGitHub/opensimQt/build/plugins/libBodyDragForce.so.so: cannot open shared object file: No such file or directory
                 Failed to load library /home/ibr/myGitHub/opensimQt/build/plugins/libBodyDragForce.so.so


Notice that the name ending is doubled libBodyDragForce.so.so

**Comment by yasseerr** [comment]
this is not expected this questions may help ?
- check for errors in the application output
- is the library  with the same OpenSim version(new built
- is the funcionality of the library working in simulation

!ignore this comment

**Comment by yasseerr** [comment]
> Notice that the name ending is doubled libBodyDragForce.so.so

that mean the library is valid bus somehow QFile::Copy add an extra extention in linux i will check for why it does that ,
meanwhile if you want to test it manualy copy it to the plugin folder

**Comment by idhamari** [comment]
It seems the error message comes from opensim not from our interface, It looks for the library name not the filename e.g. libBodyDragForce not libBodyDragForce.so so probably if you send only the libraryname to opensim it will handle the library extension based on the operating system and adds the extension e.g. ; .dll or ,so

**Comment by idhamari** [comment]
> meanwhile if you want to test it manualy copy it to the plugin folder

It is already in the plugin folder.

**Comment by yasseerr** [comment]
is the file extention valid(no duplicate) in the folder ?

**Comment by idhamari** [comment]
> is the file extention valid(no duplicate) in the folder ?

there is only one file libBodyDragForce.so I also tested the library in the folder from the terminal and it loaded successfully 

              $ opensim-cmd -L /home/ibr/myGitHub/opensimQt/build/plugins/libBodyDragForce.so pendulumDF.osim

and it outputs:

              Loaded library /home/ibr/myGitHub/opensimQt/build/plugins/libBodyDragForce.so

**Comment by yasseerr** [comment]
maybe as you specified for linux you only give the fileBaseName without the extention , it is working both ways on windows and i just pushed a code to use baseName only

**Comment by idhamari** [comment]
Where do you send the library to  opensim?

**Comment by yasseerr** [comment]
to OpenSimQt_build/plugins

**Comment by idhamari** [comment]
I think it is here :

            OpenSim::LoadOpenSimLibrary(entryInfo.filePath().toStdString());

Try to see if you can get the filename without extension and send it to opensim
  
  e.g.
   
    libName =   GetLibraryName(entryInfo.filePath().toStdString())
    OpenSim::LoadOpenSimLibrary(libName)

**Comment by yasseerr** [comment]
yes i just pushed the code for it in the navigator-features
or it still not working?

update, sorry i changed the display and missed the loading

**Comment by idhamari** [comment]
![Screenshot from 2020-07-19 19-40-23](https://user-images.githubusercontent.com/28802516/87881166-c35d5400-c9f7-11ea-839f-59da249a583b.png)

My theory was correct, I harder the path and it works:

      OpenSim::LoadOpenSimLibrary("/home/ibr/myGitHub/opensimQt/build/plugins/libBodyDragForce");

So probably you can add if else to handle this for Linux the way I suggested

**Comment by yasseerr** [comment]
yes, but now without specifiying the extention it does not work on windows , i will examine another function LoadOpenSimLibraryExact() and report back, if it does not work i will use conditions

**Comment by idhamari** [comment]
> yes, but now without specifiying the extention it does not work on windows , i will examine another function LoadOpenSimLibraryExact() and report back, if it does not work i will use conditions

As I mentioned, just simple if else to handle both windows and Linux

**Comment by yasseerr** [comment]
ok then i will use conditions and ,for the LoadOpenSimLibraryExact are ready to test in the navigator and will be overrided

**Comment by idhamari** [comment]
@yasseerr just retested again, it seems it works now as expected. Two more feedback:

* When the application starts there is still related error message  so probably this part should be handled the same way:

            $ ./opensimQt
             it is open , the file
              QSettings  "/home/ibr/myGitHub/opensimQt/build/config.ini"
              visuazer vtk  "vtkVisualiser"
              loading library:  "/home/ibr/myGitHub/opensimQt/build/plugins/libBodyDragForce.so"
             dlerror: /home/ibr/myGitHub/opensimQt/build/plugins/libBodyDragForce.so.so: cannot open shared object file: No such file or directory
             Failed to load library /home/ibr/myGitHub/opensimQt/build/plugins/libBodyDragForce.so.so
             loading library:  "/home/ibr/myGitHub/opensimQt/build/plugins/libBodyDragForce"
             Loaded library /home/ibr/myGitHub/opensimQt/build/plugins/libBodyDragForce.so

* I found another error when run the simulation:
 
             terminate called after throwing an instance of 'SimTK::Integrator::StepFailed'
              what():  SimTK Exception thrown at AbstractIntegratorRep.cpp:428:
              Integrator step failed at time 0.88854496634049573 apparently because:
              SimTK Exception thrown at AbstractIntegratorRep.cpp:547:
              Error detected by Simbody method AbstractIntegrator::takeOneStep(): Unable to advance time past 0.888545.
              (Required condition 't1 > t0' was not met.)
              Aborted (core dumped)

The error says something happened during the simulation at time 0.888 so I changed the final time to 0.1 but the error still appears which **may** means the simulation settings are not used during the simulation but I may be wrong. Please double-check this. Another important thing is to handle error that may make the application crashes. 

When this done please merge the branch to the master and close this issue. Well done and thanks again for your effort :watermelon:

**Comment by yasseerr** [comment]
thanks @idhamari and sorry for those errors as i did not install qt on linux to test it 
- for the first error see if you find in config.ini some loadOnEntry libraries saved there from previous executions 
- for the second what model are you using, because i only see one dragForce while in my case i have two to be on the same page
 - if you can test the endtime with other models to verify that the simulation parameters works, because in windows it works on the default in 3sec and  in 0.1sec, if it still not working we can have a meatings when free. as i could not replecate the error.
 - in case you are using a newer version of the plugin send it to me to test with it

> (Required condition 't1 > t0' was not met.)

here it looks like the simulation is going backward ,i will check and see if any variable initiation are missed

**Comment by idhamari** [comment]
@yasseerr 

> for the first error see if you find in config.ini some loadOnEntry libraries saved there from previous executions

Yes, the error was from an old entry. I suggest that the .ini load its content from the plugin folder each time the application starts. What do you think?

> for the second what model are you using, because i only see one dragForce while in my case i have two to be on the same page
> in case you are using a newer version of the plugin send it to me to test with it

I don't think it is related to the version as I get the same thing in the java interface but they handle it so the system get only the valid simulation time. I think what we need here is to put the simulation inside try..catch and report the error from opensim.

> if you can test the endtime with other models to verify that the simulation parameters works, because in windows it works on the default in 3sec and in 0.1sec, if it still not working we can have a meetings when free. as i could not replecate the error.

I will do more testing and report here. 


> here it looks like the simulation is going backward ,i will check and see if any variable initiation are missed

 It is expected to have such error when there is something wrong with the .osim design or the simulation setting. The simulation is an integration process that solves a system of equations. Sometimes there is wrong output or division by zero. That is why we should put this in try catch block.

**Comment by yasseerr** [comment]
> I suggest that the .ini load its content from the plugin folder each time the application starts. What do you think?

it would be easier but you will have no way to not load the library to opensim if you dont need it effect to happen(unless you delete it), not that only the libraries that are checked in the activationDialog will be loaded currently and can be removed from the config.ini when unchecked

>I don't think it is related to the version as I get the same thing in the java interface but they handle it so the system get only the valid simulation time. I think what we need here is to put the simulation inside try..catch and report the error from opensim.

> It is expected to have such error when there is something wrong with the .osim design or the simulation setting. The simulation is an integration process that solves a system of equations. Sometimes there is wrong output or division by zero. That is why we should put this in try catch block.

i will surround the simulation with try--catch to counter those bugs, 
sideeffect: it may hide undiscovered errors output in the future
