### ISSUE TITLE
MS0304: implement scaling function

### ISSUE THREAD

**Issue by idhamari** [VisSimKoblenz/opensimQt#17]
Here we will add the transformation menu:

- create/open new transform 
- modify a model based on the transform. 
- implement the scale tool as in the java interface.

**Comment by idhamari** [comment]
@yasseerr 

This is your next task. Please ignore the above and use the same concept in the java interface. You will find it in Tools>Scale model. More information can be found [here](https://simtk-confluence.stanford.edu/display/OpenSim/How+to+Use+the+Scale+Tool).

**Comment by yasseerr** [comment]
@idhamari  Ok, i will switch to it and see how it was integrated.

**Comment by idhamari** [comment]
@yasseerr  do you know when this will be completed?
