### ISSUE TITLE
MS0400: Python Part

### ISSUE THREAD

**Issue by idhamari** [VisSimKoblenz/opensimQt#19]
This is a main description for the python part:
 
The idea is to have :
* a complete opensim wrapping of somebody and opensim 
* python qt integration 

For openSimQt, this is a separate milestone with these tasks

* [x]  Integrate Python scripting in the current opensimQt interface.
   - control the interface elements.
   - control the visualizer and its element.
   - build models and run the simulation.
   - two-way access to the GUI interface.   
  - as this [answer](https://stackoverflow.com/questions/2038247/integration-of-python-console-into-a-gui-c-application) suggested, [PythonQt] (https://mevislab.github.io/pythonqt/) could be a good option.
*  [ ] Adding python plugin support.
   - actuators and plugins
   - GUI elements 
   - this part is not clear. How we do the computation in python and interact with the optimizer.
*  [x] Record and run scripts.
   - record user activity as a script.  
   - run scripts. 
   - run the interface in an invisible mode.
* [ ] Documentation
   - this should be done in parallel with each task above.
   - the documentation should use Doxygen to explain all the classes.
   - a report should be written about the implementation of different tasks.
   - a tutorial with simple examples should be added.
 

 Note for the integration part, one can check similar projects e.g. Slicer or [SALT](https://github.com/Kitware/SlicerSALT)

**Comment by yasseerr** [comment]
Hi! i didnt do much research on this but i saw that open sim has the java and the python wrapper and the wrapper should be developed for opensimQt application and we should publish the c++ classes to the python interpreter in order for them to communicate, correct me if i'm wrong

**Comment by idhamari** [comment]
OpenSim has a python and java wrapper. I think the Python wrapping is not complete. Simbody has no python wrapping except a few things provided in opensim.

The idea here is to have a complete stand-alone python version of simbody and opensim. So no need to use cpp anymore. Currently we use either cpp, python or xml to create the .osim model files. 

If we have this , it will be easier to integrate it into opensimQt project. I am not sure how the integration work technically. We should have something like this in python:

        m = getModel("myModel") # this assign the model with "myModel" name in the navigator to m
        m = getModel() # this assign the selected  model in the navigator to m

After that, we can do different GUI stuff or OpenSim stuff using python e.g closing the model or run the simulation ...etc

**Comment by idhamari** [comment]
@yasseerr  we have a new developer, Ritesh, joined our team.  Hw will work on the python part (Milestone 4). At some point when we have some progress in the python part, we will have an online meeting to share some ideas and how to process.

**Comment by yasseerr** [comment]
@idhamari  nice! and welcom for Ritesh in the project .happy to share ideas and explain when needed

**Comment by idhamari** [comment]
welcome @riteshsv  :)
