### ISSUE TITLE
MS0108_01 : BUG WrapObject Property

### ISSUE THREAD

**Issue by yasseerr** [VisSimKoblenz/opensimQt#20]
a bug accure when selecting the wrap object from the navigator more specificly trying to get the OpenSim name property unlike the other nodes.
and prevent selecting the Prob in the visualizer for the wrapobjects

**Comment by idhamari** [comment]
Please add a link to the part(s) of related the code

**Comment by yasseerr** [comment]
[vsNavigatorNode 67](https://github.com/VisSimKoblenz/opensimQt/blob/18a3b58f776e1605918bf7b48611d4bd20c8b9dc/Gui/vsModeling/vsNavigatorNode.cpp#L60)
![2020-04-22_16-47-43](https://user-images.githubusercontent.com/37770658/80003315-21de6900-84c1-11ea-83b6-eee858dafeea.png)

**Comment by yasseerr** [comment]
Update !
after some debbuggin the error happend when trying to convert std::string to QString
But: it only happen for the WrapObject  and transforms 
the pointer for the WrapObject does not contain informations about the object but only when called in the setupPropertiesModel and when it called from vsWrapObjectNode it has all the values set up
so problem still open!

**Comment by idhamari** [comment]
@yasseerr 

If you like we can skype to discuss this. It is not clear to me what is the bug here.

I just downloaded and built the recent version. Here are some comments:

* it seems the slow problem is gone. 
* The event handler of the vtk widget has some problems as sometimes geometry disappears.
  - Usually there already some events pre-defined so we need to override them.
  - check if there are similar examples.
* when we reload the model , the small icons and the ground disappear.    

I think what we need is to have our own Qt-VTK-Widget class that inherits and overrides the current functions:
  - the widget has opensim small icons and their functions by default
  - different observers that monitor the mouse event in the widget to decide the action based on the mouse event  e.g. move, click, drag, ..etc
 - each object in the widget should have some properties:
    - visible
    - selected
      - if selected, its color should be changed to e.g. orange
    - type  e.g. model object or widget object
      - widget object: these small icons on the top left in addition to the skybox and the ground.
      - model object: geometry, joints, ...
 - based on these properties we define different actions

**Comment by idhamari** [comment]
@yasseerr 

Here is what I found, check my last comment:

We can use something like 

     bool isEmptyName = true;
     if(openSimObject != nullptr){
        isEmptyName = (openSimObject->getName()=="");
        if (not isEmptyName ){
             // get object properties
       else{
            //get object properties using a different method
       }     

Using the above if-else allows the application to continue without crashing. Still, we need to find how to get the object properties.  An idea is to get the navigator parent node of this object then handle this object using its parent object and the current navigator node name.

**Comment by yasseerr** [comment]
@idhamari 
yes that would work but the core problem is you can't test it when you call opensimObject->getName() the program crashes

**Comment by idhamari** [comment]
@yasseerr 

I don't have this in Linux using [this code](https://github.com/VisSimKoblenz/opensimQt/files/4535048/vsNavigatorNode.txt). In the navigator, I select  jointset  ---> r_elbow ---> rotation1 and the program does not crash.

Could you please describe or record a short video to show this using the arm model.

**Comment by yasseerr** [comment]
did you test it on the transforms and the wrap objects , for windows it still crashes but not on the rotations as in this [video](https://drive.google.com/open?id=12A70jRPRdimZ_7zrxOPZYJhsq3vqgUsA)

**Comment by idhamari** [comment]
@yasseerr 
Thanks for sharing the video. 

This is the output when  I select TRIlonghh

     bug here ================================ start
     Object
     TRIlonghh
     0
     bug here ================================ end
    "TRIlonghh"
     VisSim: line 92 ........................
     VisSim: Getting object properties ........................
     Segmentation fault (core dumped)

This means we get the name property and the error happens somewhere after that. Also, I suggest:
*  uploading your work so I can test using the same source-code. 
* do the testing outside qtcreator e.g. run the application form a windows terminal. I had problems in the past running directly from inside qtcreator.

**Comment by yasseerr** [comment]
@idhamari 
you're welcom!
for the code you mean the to upload the code with the changes you sent because i already uploded the last version, and i will try to run it outside of qt creator.
note that for me it crashed before the name like this
Loaded model arm26 from file F:/arm26.osim
bug here ================================ start
Object
01:46:23: The program has unexpectedly finished.
and only sometimes that it manage to get the name

**Comment by idhamari** [comment]
The code I am using is from before our last skype. I see now, you already pushed new code. I will use it on my testing. I will also test this on windows.

**Comment by idhamari** [comment]
@yasseerr 

I can confirm that the bug exists in windows and I have different behavior than Linux. I will investigate that.

I also found out that there is a path problem when running using different environment e.g. Linux, Visual studio or QtCreator.

      ERROR: In D:\sw\vtk-9.0.0.rc3\src\IO\Image\vtkPNGReader.cxx, line 264
      vtkPNGReader (00000211C2DB2360): Unable to open file ./vtk_images/zoom-in.png

 This should be fixed now so we don't keep doing the same thing again and again. Please do:

1. Create an initial file e.g. vsOpenSimQt.ini inside the Gui folder. This file should contain important paths e.g. Geometry path, images , icons, ....etc.   
2. CMake should copy this file to the same location of the target exe file
3. Cpp files should read the paths using this file instead of hard-coded paths. 

When this is done, please inform me here so I can continue investigating the bug.

**Comment by idhamari** [comment]
@yasseerr 

Update:

As I understood:

- user select a node in the navigator 
- this triggers void vsModelNode::setupPropertiesModel(vsPropertyModel *model)
- which calls    void vsNavigatorNode::setupPropertiesModel(vsPropertyModel *model){

What is not clear: 

- why we have the same function name? I suggest change to setupPropertiesModelNode 
- how the functions knows which node is selected? 
- how the node object is connected to the openSimObject?
 

I tried this but each time I get a different number for the same object, do you know why? it seems to me there is something wrong with these pointers when they are generated.

```cpp
void vsNavigatorNode::setupPropertiesModel(vsPropertyModel *model){
	bool isEmptyName = true;
	if (openSimObject != nullptr) {
		//name property
		//qDebug() << QString::fromStdString(openSimObject->getName());
		//qDebug() << QString::fromStdString(openSimObject->getName());
		std::cout << "bug here ================================ start" << std::endl;
		std::cout << openSimObject->getClassName() << std::endl;
		std::cout << openSimObject->getNumProperties() << std::endl;
		//std::cout << openSimObject->getName() << std::endl;
		//isEmptyName = (openSimObject->getName() == "");
		isEmptyName = (openSimObject->getNumProperties()<=0) | (openSimObject->getNumProperties() > 1000);
		std::cout << isEmptyName << std::endl;
		std::cout << "bug here ================================ end" << std::endl;
		/* windows test
           bodyset ---->base ----> Trilongglen  name ="" ok
		   jointset ---->r_elbow ----> rotation1, can not get the name, "Segmentation Fault"  

		*/
		vsPropertyItem *nameItem = new vsPropertyItem();
		//qDebug() << QString::fromLatin1(openSimObject->getName(),(int)openSimObject->getName().size());

		if (! isEmptyName) {
				std::cout << "VisSim: Getting object prperties ........................" << std::endl;
				nameItem->m_name = "name";
				std::string nameTmp = openSimObject->getName();
				nameItem->m_value = QString::fromStdString(nameTmp);
				qDebug() << nameItem->m_value;
				nameItem->m_type = vsPropertyItem::Text;
				nameItem->setText(nameItem->m_value);
				model->m_propertiesItem->appendRow(QList<QStandardItem*>() << new QStandardItem("name") << nameItem);

				//type property
				vsPropertyItem *typeItem = new vsPropertyItem();
				typeItem->m_name = "type";
				typeItem->m_isEditable = false;
				std::string typeTmp = openSimObject->getConcreteClassName();
				typeItem->m_value = QString::fromStdString(typeTmp);
				typeItem->m_type = vsPropertyItem::Text;
				typeItem->setText(typeItem->m_value);
				model->m_propertiesItem->appendRow(QList<QStandardItem*>() << new QStandardItem("type") << typeItem);

				for (int i = 0; i < openSimObject->getNumProperties(); ++i) {

					auto ap = &openSimObject->getPropertyByIndex(i);
					QString apName = QString::fromStdString(ap->getName());
					vsPropertyItem *apItem = new vsPropertyItem();
					QStandardItem *apNameItem = new QStandardItem(apName);
					qDebug() << apName << QString::fromStdString(ap->getTypeName());

					if (ap->isListProperty()) {

						apItem->m_type = vsPropertyItem::List;
						QString listRepresentation = "[ ";
						for (int j = 0; j < ap->size(); ++j) {
							listRepresentation += QString::fromStdString(ap->getValueAsObject(j).getConcreteClassName());
							listRepresentation += " ";
						}
						if (ap->size() == 0) listRepresentation += " empty ";
						listRepresentation += "]";
						apItem->m_value = listRepresentation;
						apItem->setText(apItem->m_value);
					}
					//            else if(ap->isOptionalProperty()){

					//            }
					//            else if(ap->isUnnamedProperty()){\
					//            }
					else if (ap->isObjectProperty()) {
						if (OpenSim::Function::safeDownCast(const_cast<OpenSim::Object*>(&ap->getValueAsObject()))) {
							qDebug() << "it is a function indeed";
						}
						else if (apName == "Appearance") {
							auto _appr = &ap->getValueAsObject();
							auto appr = OpenSim::Appearance::safeDownCast(const_cast<OpenSim::Object*>(_appr));
							//visible property
							auto visibleProp = &appr->getProperty_visible();
							vsPropertyItem *visibleItem = new vsPropertyItem();
							QStandardItem *visibleNameItem = new QStandardItem("visible");
							visibleItem->m_type = vsPropertyItem::Check;
							visibleItem->m_value = QString::fromStdString(visibleProp->toString());
							visibleItem->setText(visibleItem->m_value);
							visibleItem->setEditable(true);
							model->m_appearancexItem->appendRow(QList<QStandardItem*>() << visibleNameItem << visibleItem);

							//opacity property
							auto opacityProp = &appr->getProperty_opacity();
							vsPropertyItem *opacityItem = new vsPropertyItem();
							QStandardItem *opacityNameItem = new QStandardItem("opacity");
							opacityItem->m_type = vsPropertyItem::Text;
							opacityItem->m_value = QString::fromStdString(opacityProp->toString());
							opacityItem->setText(opacityItem->m_value);
							opacityItem->setEditable(true);
							model->m_appearancexItem->appendRow(QList<QStandardItem*>() << opacityNameItem << opacityItem);

							//color property
							auto colorProp = &appr->getProperty_color();
							vsPropertyItem *colorItem = new vsPropertyItem();
							QStandardItem *colorNameItem = new QStandardItem("color");
							colorItem->m_type = vsPropertyItem::Color;
							colorItem->m_value = QString::fromStdString(colorProp->toString());
							colorItem->setText(colorItem->m_value);
							colorItem->setEditable(true);
							model->m_appearancexItem->appendRow(QList<QStandardItem*>() << colorNameItem << colorItem);

							//color property
							auto dpProp = &appr->getProperty_SurfaceProperties();
							vsPropertyItem *dpItem = new vsPropertyItem();
							QStandardItem *dpNameItem = new QStandardItem("DisplayPreferences");
							dpItem->m_type = vsPropertyItem::Text;
							dpItem->m_value = QString::fromStdString(dpProp->toString());
							dpItem->setText(dpItem->m_value);
							dpItem->setEditable(true);
							model->m_appearancexItem->appendRow(QList<QStandardItem*>() << dpNameItem << dpItem);

							continue;
						}
						else {
							apItem->m_type = vsPropertyItem::Object;
							apItem->m_object = const_cast<OpenSim::Object*>(&ap->getValueAsObject());
							apItem->setText(QString::fromStdString(apItem->m_object->getName()));
							apItem->setEditable(false);
						}
					}
					else {
						apItem->m_type = vsPropertyItem::Text;
						apItem->m_value = QString::fromStdString(ap->toStringForDisplay(1));
						apItem->setText(apItem->m_value);
					}

					QRegExp socketRegEx("^socket.*");
					if (socketRegEx.exactMatch(apName)) {
						model->m_socketsItem->appendRow(QList<QStandardItem*>() << apNameItem << apItem);
					}
					else {
						model->m_propertiesItem->appendRow(QList<QStandardItem*>() << apNameItem << apItem);
					}

				}

		}
    }
	std::cout << "VisSim: Getting object prperties is done ........................" << std::endl;
```

**Comment by yasseerr** [comment]
thanks for the feedback!
to understand how the nodes and models work you should understand Qt Model/View to represent the data
* 1:  how the function knows which node is selected
  * when you click on the treeview it triggers  a signal that will call the onNavigatorClicked in the vsMainWindow which give you the index of the node QModelIndex
 * after that the helper funcion nodeForIndex() give you the node that was clicked which inherit vsNavigatorNode it can be all the other nodes using simple polymorphism 
 * that node when it was created in the constructor it was given the openSimObject that represent it so it can do operation on it

* 2 : for the function name we are using the same function name because it is the same function overrided in the modelNode as every other node using inheretance so when you click the function corresponded to the node type(model,body...) will be call if it was not ovverided in the class the default one in vsNavigatorNode will be called

* 3: opensimObject is connected  when we add a new model like this 
 * the modelNode is created and connected to the  OpenSim::Model which inherit OpenSim::Object 
 * the modelNode create subNodes like ground bodysetsNode
 * the bodyset create the bodies and assign a OpenSim::Body to the openSimObject ..ex

**Comment by yasseerr** [comment]
for the image please make sure you have the latest version clean the project  and run cmake , it should copy the zoom image to it's appropriate folder , because there in no hardcore path added vtk cant use qt resources  files qrc/rcc(compiled) so its images are put in target/vtk_images unlike the others

**Comment by idhamari** [comment]
Thanks for the info. 

> for the image please make sure you have the latest version clean the project and run cmake , it should copy the zoom image to it's appropriate folder , 

In visual studio the application is inside build\release so this does not work.  I already solved this manually for now. 

We will need the .ini file in the future for other things as well. When we have a lot of paths hard-coded this will make a problem if we need to reconstruct our repository. The standard is to read the paths and the settings from a .ini file. So it is better to do it now.

> to understand how the nodes and models work you should understand Qt Model/View to represent the data

It seems that you are following the java interface approach. Maybe the bug comes from a difference between java and cpp pointers handling? I was hopping we are handling this our way e.g. by reading the text osim file and create the nodes. This gives us more control and more independent from OpenSim.    

Please make sure that each node in the navigator is correctly connected to only one pointer and this pointer is the correct pointer to the related OpenSim object.

I will try to investigate more about the bug.

**Comment by yasseerr** [comment]
* for the ini file QSetting give you the option to store the settings in the ini file or system registry
a static instance of it will be in vsOpenSimTools to store the settings
* for the openSimObject they should be connected even for wrapobject as you can print the name normaly on other parts of the code except in the setupPropertiesModel function which is the abnormal behavior that we trying to solve
* we need further look into the OpenSim::WrapObject and rotation to see what special about them
