### ISSUE TITLE
MS0201_01 : BUG some muscle objects position is incorrect when load or play motion

### ISSUE THREAD

**Issue by idhamari** [VisSimKoblenz/opensimQt#21]
@idhamari will do more testing and try to handle this.

**Comment by idhamari** [comment]
@yasseerr mentioned: 

>  just a note i found out that when i recreate the vtk actors each frame instead of just changing the coordinates ,rotaion and display properties the problem go away . It is done like that in netbeans but it causes a huge lack of performance when implemented in vtk. so that muscle is a performance optimization issue, and i will try and find how to mix the two solutions to avoid the muscle being rendered. after finishing the Simulation.

Probably we need to check vtk discourse forum if there are some tricks to increase the performance.

**Comment by yasseerr** [comment]
i think the bug is fixed, the problem is that some object where ignored in some frames so they where not updated, a map to check that the actor/prop where updated is added and change the appearance accordingly.

**Comment by idhamari** [comment]
Excellent, I will test it and add feed back if needed.
