### ISSUE TITLE
MS0306: Documentation of current progress

### ISSUE THREAD

**Issue by idhamari** [VisSimKoblenz/opensimQt#25]
@yasseerr 

These are the new tasks for the next milestone:

* [x] inverse kinematics (this could be one of the examples, check the third task bellow )
      - we use a tab next to the visualizer. This tab contains multi-tab for all related to this tool menu
      - the tab should be visible only when user select this tool
      - I think the tool create xml file and use it. 
      - an example will be provided here: [model file](https://github.com/VisSimKoblenz/opensim-models/blob/master/Pipelines/Gait2354_Simbody/OutputReference/subject01_simbody.osim), [.trc file](https://github.com/VisSimKoblenz/opensim-models/blob/master/Pipelines/Gait2354_Simbody/subject01_walk1.trc), and the [XML file](https://github.com/VisSimKoblenz/opensim-models/blob/master/Pipelines/Gait2354_Simbody/subject01_Setup_IK.xml). More information can be found [here](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Getting+Started+with+Inverse+Kinematics)
* [x] fix bugs 
      - the system crashes and not stable we need to check all the situations that may produce an error and add try..catch 
      - check if vtk objects destroyed correctly when they are not used.
     - fix bugs: libpng warning: iCCP: known incorrect sRGB profile (done! the png files are fixed and will be pushed in next commit)
    - others? 
* [x] documentation: the main reason for this tool is to provide developers with a simple interface that can be extended in a simple way. 
   - implement the actions for the help menu similar to the jave interface. A web browser tab next to the visualizer should be used. 
   - add oxygen documentation for  our interface API.
   - add simple tutorials to show how we can extend the interface to do more stuff.
     - add the inverse kinematic tool
     - add preferences (or anything simple)
     - add body and a joint that one can customised e.g. to create double pendulum from the simple pendulum (the plugin force should not be used here to make thing s simple)

**Comment by yasseerr** [comment]
hi @idhamari 
the close and reopen bug was fixed and some other vtk and simulation cleaning if you want to test it .

**Comment by idhamari** [comment]
well done @yasseerr  I will test and report if needed.

**Comment by yasseerr** [comment]
@idhamari 
update!
the doxigen files are created , all what is left is the documentation of all the classes/and functions and the link between them . returning to it soon
also if you have the logo of the application to place it in the documentation and the app, that would be nice
![2020-08-05_20-54-17](https://user-images.githubusercontent.com/37770658/89480420-9057e600-d795-11ea-9dbe-23a1cfe26193.png)

**Comment by idhamari** [comment]
@yasseerr 

> the doxigen files are created , all what is left is the documentation of all the classes/and functions and the link between them. 

well done :watermelon: 


> also if you have the logo of the application to place it in the documentation and the app, that would be nice

Probably we will use a modified one from the original to keep the credits of the original developers and add ours. I will add one soon. 

> returning to it soon

take your time :)

**Comment by idhamari** [comment]
I checked the doxygen implementation today.  It would be nice:

  *  the Doxyfile uses a relative path instead of the hard-path for the input and the output.
  *  having an option in CMakeLists to build the documentation, if it is enabled then the documentation is built.

For now, these are not important, I added them as a reminder.

**Comment by yasseerr** [comment]
@idhamari 
agree, to make it easy to have the documentation documents i will try to add a chunk of cmake code to handle the build of doxygen, just like some other libraries (simtk,opensim) , that uses relative path and check the installation of doxygen

**Comment by idhamari** [comment]
@yasseerr how is the tutorial for inverse kinematics? please let me know if there is something not clear.

**Comment by yasseerr** [comment]
Hi @idhamari  
everything is clear , it  just  that i got stuck in writing documents and presentations and will continue right after.
and your patience is appreciated

**Comment by idhamari** [comment]
@yasseerr when can we have an online meeting?

**Comment by yasseerr** [comment]
Hi @idhamari !
i'm ready for a meeting  whenever you have time

**Comment by yasseerr** [comment]
hi @idhamari 
i think the Inverse Kinematics tool is ready , and it can be tested in the master branch . for the videos i will edit and upload the videos after it , althought i think they are kind of long to be used for quick understanding 458 minute to be exact as the Inverse Kinematics tool contains some complexity between the coordinates/markers/tool/output to solve.

**Comment by idhamari** [comment]
@yasseerr 

> i think the Inverse Kinematics tool is ready , and it can be tested in the master branch .

well done! I will test it and report. For now, please cooperate with @riteshsv on the python plugin part. 

> for the videos i will edit and upload the videos after it , althought i think they are kind of long to be used for quick understanding 458 minute to be exact as the Inverse Kinematics tool contains some complexity between the coordinates/markers/tool/output to solve.

485 minutes is too long, could you please share a link via skype for the current video. I will have a look and try to find a way to reduce it.

**Comment by idhamari** [comment]
@yasseerr I just tested the tool using [subject01_IK.zip](https://github.com/VisSimKoblenz/opensimQt/files/5390214/subject01_IK.zip). 

The file run without problem using the terminal

          opensim-cmd run-tool subject01_Setup_IK.xml

but it does not run in both java and qt guis with different error messages:

![Screenshot from 2020-10-16 10-25-59](https://user-images.githubusercontent.com/28802516/96235204-c9cd7e80-0f9a-11eb-8588-f069de135dc3.png)

![Screenshot from 2020-10-16 10-26-47](https://user-images.githubusercontent.com/28802516/96235208-ca661500-0f9a-11eb-9605-7273e5e2f27a.png)

I think I had a similar problem in the past and report it [here](https://github.com/opensim-org/opensim-core/issues/2643).

Since this probably is related to opensim-core, we can use the terminal as a simple  work-around, please 

* Add a new button next to "Run" and call it "Run in Terminal"
* The button action:
  - execute  

        opensim-cmd run-tool  "the_loaded_file.xml"

  - load the motion file and animate it

**Comment by yasseerr** [comment]
@idhamari 
this is an easy fix , just go to the markers table and disable the values with Not_Found_in_file , then you can run the tool because those values were not present. if you want to go with the cmd command you can't create new xml files with new values, but with this you can change the values and save them , if it is still not what you want in the software we will switch to the cmd solution.

**Comment by idhamari** [comment]
@yasseerr 

> this is an easy fix , just go to the markers table and disable the values with Not_Found_in_file , then you can run the tool because those values were not present. 

I tried this but it does not work. please create a short video for this, maybe I did it wrong?

> if you want to go with the cmd command you can't create new xml files with new values, but with this you can change the values and save them , if it is still not what you want in the software we will switch to the cmd solution.

We will use this in case the above doesn ot work.

**Comment by yasseerr** [comment]
@idhamari 
I tried it with the file you provided and their was a difference in representing a no-coordinate configuration inside the config file between "Unassigned" and "" . pull the latest commit and it should work as in the video [LINK](https://drive.google.com/file/d/1aeyjx7zQUB-xenR0t4KgpZLMTr7bn5Dd/view?usp=sharing)

**Comment by yasseerr** [comment]
i missed those two messages.
> well done! I will test it and report. For now, please cooperate with @riteshsv on the python plugin part.

thanks , and i will check the python plugin, and  @riteshsv tag me whenever there is a task or a solution to investigate

> 485 minutes is too long, could you please share a link via skype for the current video. I will have a look and try to find a way to reduce it.

Ok , i will share the link  after labeling-ordering and uploading them

**Comment by idhamari** [comment]
@yasseerr 

I used the last commit and used it the same way but still I get an error:

`
InverseKinematicsTool Failed: Timestamp at row 0 with value 0,000000 is greater-than/equal to timestamp at row 1 with value 0,000000
	Thrown at TimeSeriesTable.h:492 in validateRow().
terminate called after throwing an instance of 'OpenSim::Exception'
  what():  InverseKinematicsTool Failed, please see messages window for details...
Aborted (core dumped)
ibr@ibr-MS-7C35:~/myGitL
`

**Comment by yasseerr** [comment]
@idhamari 
try change the timestamp or time range if it not working  test with the file opensim-gui\opensim-models\Pipelines\Gait2354_Simbody  . if it still not working i will try and investigate the bug link, maybe it is the opensim-core installation

**Comment by idhamari** [comment]
@yasseerr Thanks for your quick response. I asked myself why it runs correctly in the terminal. German locale represents numbers in a different way e.g. the floating-point symbol is comma not dot. I changed the regional setting from German to English and restarted the session. It works now in both java and qt interfaces.  

> just go to the markers table and disable the values with Not_Found_in_file

I noticed that the values are already disabled in the java gui so could you please implement this part in qt gui as well. Also please animate the motion file after it generated and loaded.

**Comment by yasseerr** [comment]
@idhamari  your welcome.

> I noticed that the values are already disabled in the java gui so could you please implement this part in qt gui as well. Also please animate the motion file after it generated and loaded.

i'm currently editing the speed of the recordings and will disable not_found_in_file values right after it finishes
