### ISSUE TITLE
MS0401_T0202 Python: opensim Python and Qt GUI communications

### ISSUE THREAD

**Issue by riteshsv** [VisSimKoblenz/opensimQt#27]
With reference to #24 
[ref: MS0401_T02](https://github.com/VisSimKoblenz/opensimQt/issues/24#issuecomment-674016781)
Further steps to achieve python integration after completing #26 
- **Visualization:**
    - To set the model which was created from Python and sync with the openSimQt cpp model.
    - [x] call set setModelFromPython

- **Simulation setting**
    - Update simulation settings to the UI from Python. Pre-condition: only if the model is updated and set.
    - [x] write our own python function

        vsPyManager.setAccurayc()
        vsPyManager.UpdateGui()
    - [x] call our python manager function vsPyManager.UpdateGui()

**Comment by riteshsv** [comment]
>@idhamari I also noticed that the simulation setting part is still missing from the previous task. Is there a difficulty to implement it? if so, we can meet online next week and discuss some solutions. 

I am working on it and will complete tomorrow. No issues.

**Comment by riteshsv** [comment]
@idhamari 
I have completed the vsManager Task for Python. It can be tested as below:

## Before
![sim_before](https://user-images.githubusercontent.com/39936429/93510249-81d91e80-f93e-11ea-8aa9-3ae67ba81a9d.png)

## Test:
```
vsManager.setAccuracy(0.002)
vsManager.setStepSize(0.01)
vsManager.setEndTime(7)
vsManager.setIntegratorMethod(vsManager.SemiExplicitEuler2)
vsManager.updSimDataToGui()

```
## After
![sim_after](https://user-images.githubusercontent.com/39936429/93510825-7508fa80-f93f-11ea-8060-9d1c29811c37.png)

I have pushed the code. 
I would like to discuss a few items with you. please let me know your convenient time.

**Comment by riteshsv** [comment]
@idhamari  Also, I have completed half documentation, will finish the remaining in a day or two. Yasser as going to give the license/copyright template. But not received the same.

**Comment by idhamari** [comment]
@riteshsv 

> I have completed the vsManager Task for Python. It can be tested as below:

well done! I will test it soon and add feedback if needed.

> I would like to discuss a few items with you. please let me know your convenient time.

Tomorrow at 11:00 German time?

**Comment by riteshsv** [comment]
@idhamari 
> Tomorrow at 11:00 German time?

That would by 2:30 pm my time. I will be available.

**Comment by riteshsv** [comment]
@idhamari 
I have created below license template. If you think its ok, I will incorporate it in Qt.

[license.txt](https://github.com/VisSimKoblenz/opensimQt/files/5243470/license.txt)

**Comment by idhamari** [comment]
> That would by 2:30 pm my time. I will be available.

great! see you later.
