### ISSUE TITLE
MS0401_T03 Python: GUI macro recording

### ISSUE THREAD

**Issue by riteshsv** [VisSimKoblenz/opensimQt#28]
GUI Macro recording and Playback
- [x] Record Macro (Start,Pause and Stop Recording)
- [x] Play Back recorded macro
- [x] Save macro script file (python script)
- [x] Load recorded macro and Run
- [x] Testing
- [x] Commit code

**Comment by riteshsv** [comment]
@idhamari 
I have completed & tested the Macro recording. Below is the sequence of tests:
Testing Sequence:
- [x] Upon opening the application Record Macro is enabled, Pause, Stop disabled
- [x] On click of Record Macro button or menu selection, Record Macro disabled, Pause, Stop enabled
- [x] All GUI actions and Python console commands, after record are recorded.
- [x] On Pause button , GUI and python commands are not recorded, but session is paused. Record and Stop buttons enabled
- [x] Restart recording by clicking Record button after pause, user may also stop recording
- [x] On Stop recording, "file save dialog" appears. choose location and type file name. saves default .py files.
- [x] On Run Current Script, latest script recored is Run. If no script is in the session then message is displayed.
- [x] On Run button click, "file open" dialog appears, which allows for opening *.py script files. Macro files can be opened and executed. On selection of file, script is automatically run.

**Comment by riteshsv** [comment]
@idhamari 
Below mentioned features implemented

GUI Macro Recording Functionality

openSimQt provides Macro recording functionality which allows users to record the GUI actions (commands) in form of a script. By this way users can record a script for repeating steps and automate the process. Such script could be saved to disk and loaded at any time through the openSimQt GUI, to run.

Caution: The script is a python script and uses openSimQt python api. Hence it's usage outside the openSimQt GUI is not supported.

Below are the features provided by GUI Macro Recording Module:

- Record Macro (Start Recording)
    - Menu: Scripts > Record Macro
    - Toolbar: Record icon on Scripts Toolbar
    - Starts the a recording session. All GUI Actions and commands in Python Scripting Console will be recorded.
- Pause Recording
    - Menu: Scripts > Pause Recording
    - Toolbar: Pause icon on Scripts Toolbar
    - Pauses the recording session.
- Stop Recording
    - Menu: Scripts > Stop Recording
    - Toolbar: Stop icon on Scripts Toolbar
    - Stops the recording session and prompts for file storage location and file name. By default the ".py" extension will be added. Users don't have to type the extension.
- Run Current Script
    - Menu: Scripts > Run Current Script
    - Toolbar: Run Current Script
    - Runs the last recorded macro in active session of openSimQt.
- Run Macro
    - Menu: Scripts > Run
    - Toolbar: Run on the Scripts Toolbar
    - Presents the open file dialog and prompts user to open the script file of desired macro. Runs the file so selected by the user.

**Comment by riteshsv** [comment]
@idhamari  : Code committed. Will work on one pending task from another issue.

**Comment by idhamari** [comment]
@riteshsv thanks for your effort, this sounds great. :watermelon:

I still don't see any new commits. It would be nice if you push your work then write here a summary of the progress and add a link to the related commit. 

I also noticed that the simulation setting part is still missing from the previous task. Is there a difficulty to implement it? if so, we can meet online next week and discuss some solutions.

**Comment by idhamari** [comment]
@riteshsv ok, I see you already pushed the code :) I will test and feedback if needed.

**Comment by idhamari** [comment]
@riteshsv 

I found some bugs:

>  vsMacroManager.h:71:17: error: ‘mutex’ in namespace ‘std’ does not name a type   static std::mutex _mutex;

solved by  adding this line to vsMacroManager.h:

       #include <mutex>

>  vsMacroManager.cpp:130:130: error: ‘endl’ is not a member of ‘Qt’
                out << "#################################################################################################" << Qt::endl;

still investigating, if you know a solution please share.

**Comment by riteshsv** [comment]
@idhamari 
QTextStream endl  is deprecated since 5.15. 
Q_CORE_EXPORT QT_DEPRECATED_VERSION_X(5, 15, "Use Qt::endl") QTextStream &endl(QTextStream &s);

so its a version issue. I will test it by replacing it with '\n' and report back

**Comment by idhamari** [comment]
@riteshsv 

After a long fight, I was able to win and solve the bugs :) please check the last commit in the master. 

It seem cmake has problem handling multiple versions of python. For now I used an older cmake functions and set python manually. Please check the updated cmake and code and see if it works on your mac (you may modify it in away that works also in my machine as well).
