### ISSUE TITLE
MS0501 write a friendly build script

### ISSUE THREAD

**Issue by idhamari** [VisSimKoblenz/opensimQt#30]
* [ ] fork required repositories:   
     - OpenSim and its deps. (already done) 
     - VTK9 
     - PythonQt
        - Shall we switch to PySide? or something else? 
          - two important things: 1. it works 2. long support
     - since some are important it is better to save them locally and provide the original links for reference, 
          - Python 
          - Cmake     
* [ ] write a script to download the sources and build them. 
     - specify the exact version recommendations.
     - script should be cross-platform Win, Mac, Linux
     - user selects the location for the build and the script creates all the relative folders.
     - re-write CMake to handle different systems.
       - we should add options for the user to get more flexibility:
         - use local libs if available
         - download binaries or build from source e.g. cmake, vtk, ... 
* [ ] test the script using a clean system e.g. vmware. 
     - add the tested system to the recommendation list.

**Comment by riteshsv** [comment]
## Embedding Python
  - Problem: 
    - Python would be installed on most computers hence embedding pythonlibs is undesirable
    - Also, this will constraint to the use of only one version of Python. Ideally application should be compatible with multiple minor versions of python. That makes it versatile. (Taking into consideration that Python 2 is officially unsupported, this point refers to multiple minor versions of Python 3)
  - Solution:
    - CMake Script to find Python installation starting from highest version, falling back to lower minor versions, till it finds one.
  - Strategy:
      - Find Package in Module mode / then in Config mode, if not found, get Python_DIR path from user which contains Python CMake file

I am working on a solution that will search for python (all available installed versions of Python 3.x and install the highest version. Also, giving option to user to set python path to override the default

**Comment by idhamari** [comment]
@riteshsv Thanks for your feedback. The plug-in task is more important now so please concentrate on it.
