### ISSUE TITLE
MS402 python plugin 

### ISSUE THREAD

**Issue by idhamari** [VisSimKoblenz/opensimQt#31]
* Currently to add new opensim objects one needs to write a cpp code that generates a library e.g. the BodyDragForce library. 
* This library then loaded to opensim to be used.
* The goal of this task to replace the use of the library by using simple python script e.g. add a new element to the tool menu "Load Python Plugin". 
   - this will help to avoid working with cpp by non-programmers users and avoid the need for compilation anymore.

useful reference: https://simtk-confluence.stanford.edu:8443/display/OpenSim/Using+Plugins

some workaround ideas:
* using cpp builder.
  - uses a cpp template e.g. a button that creates new plugin
    - during this, we search the system for available compitable cpp compiler, if not found, a dialog should appear for the user t define the location. 
  - the user modified the cpp for his need. 
  - the user press build plugin button to compile the cpp file, generate the library and load it to opensimQt.

**Comment by idhamari** [comment]
@riteshsv how is everything so far?

**Comment by riteshsv** [comment]
@idhamari I am working on the plugin part and have found a solution. I start testing it tomorrow and provide you with a feedback.

**Comment by idhamari** [comment]
@riteshsv sounds great! looking forward to seeing it.

**Comment by idhamari** [comment]
@riteshsv is there an update regarding this issue?  the deadline is the end of this month.

**Comment by riteshsv** [comment]
@idhamari I am working on the same. not able to get a breakthrough. i am still trying.

**Comment by idhamari** [comment]
@riteshsv as I mentioned before it is very challenging task to be done by one person in the provided time, that is why I suggested you contact @yasseerr and cooperate to complete it. Please arrange an online meeting to discuss with him how to proceed.

**Comment by riteshsv** [comment]
@idhamari I agree with you. I will discuss with @yasseerr. I am onto a task today, and will discuss with yasseer tomorrow or as and when he has time. I will speak to him.

**Comment by idhamari** [comment]
@riteshsv @yasseerr what about we meet to discuss this tomorrow at 18:00 German time? (note that we are in winter-time now)

**Comment by yasseerr** [comment]
@idhamari  @riteshsv  i'm down to discuss it tomorrow 18:00 GMT+2

**Comment by idhamari** [comment]
@yasseerr if we don't hear from @riteshsv  until 16:00 German time, then the meeting is canceled.

**Comment by riteshsv** [comment]
@idhamari @yasseerr I am sorry folks. I was down with fever and my sinusitis symptoms were aggravated. Please let me know your convenient time to discuss.

**Comment by idhamari** [comment]
@riteshsv sorry to hear that, I hope you feel better now. If you like we can meet today or tomorrow at 18:00 German time. @yasseerr do you have time?

**Comment by riteshsv** [comment]
18:00 CET is 10:30 pm my time. I dont mind doing it but it will be too late
for me. I am ok, if @yasseerr has is available.

**Comment by idhamari** [comment]
@riteshsv @yasseerr 
what about 15:00 German time?  this should be 19:30 your time.

**Comment by riteshsv** [comment]
@idhamari @yasseerr
its fine. I will be available

**Comment by yasseerr** [comment]
@riteshsv @idhamari 
Hi i dont think i will be connected tommorow (outside trip), it it was canceled i will join you at 15:00

**Comment by riteshsv** [comment]
@idhamari I tried but could not get it working. It is not impossible, but just that I am not sure how long it will take to make it work. So, i think, we should drop the idea for now and move forward. I will keep a tab over my ideas and as soon as i get something I will try. 

Also, you might be aware that we have diwali, our biggest festival. So, I will be on holiday for a week now. 
Apart from that I would like to take a break till the end of December 2020, because I have to prepare for IELTS exams. planning to immigrate to Canada.

**Comment by idhamari** [comment]
>I tried but could not get it working. It is not impossible, but just that I am not sure how long it will take to make it work. So, i think, we should drop the idea for now and move forward. I will keep a tab over my ideas and as soon as i get something I will try.

Yes, we can do this.

> Also, you might be aware that we have diwali, our biggest festival. So, I will be on holiday for a week now.
Apart from that I would like to take a break till the end of December 2020, because I have to prepare for IELTS exams. planning to immigrate to Canada.

@riteshsv sure :)

if you are available, let's have a short skype now.

**Comment by riteshsv** [comment]
@idhamari I have a meeting with my ceo in few min. Can we have a call around 18:00 German time. If it is convenient to you 

Regards 
Ritesh Sangani

**Comment by idhamari** [comment]
>@idhamari I have a meeting with my ceo in few min. Can we have a call around 18:00 German time. If it is convenient to you


@riteshsv  probably I will be available. I already wrote some suggestions please reply there when you read them.
