### ISSUE TITLE
MS0104: open file by drag and drop

### ISSUE THREAD

**Issue by idhamari** [VisSimKoblenz/opensimQt#4]
* User can drag and drop a model, model element, mesh file to the application window.
* The element should be loaded to the navigator and the visualizer as well.

**Comment by yasseerr** [comment]
completed except for the visualizer part
Note that windows prevent dnd when runing the software from QtCreator so copy the executable to msvc20xx/bin to see how it runs in deploy mode
https://stackoverflow.com/questions/37828617/drag-and-drop-not-working-if-application-lies-in-specific-directory
not tested on linux 
![2020-02-17_2-42-48](https://user-images.githubusercontent.com/37770658/74618045-6bf94600-5130-11ea-90dc-c670cce95c75.gif)

**Comment by idhamari** [comment]
@yasseerr 

Well done! I still can not test it because of the error I get from the previous task.

**Comment by idhamari** [comment]
This issue is closed now and will be open later if needed.
