### ISSUE TITLE
MS0105: reload current scene function.

### ISSUE THREAD

**Issue by idhamari** [VisSimKoblenz/opensimQt#5]
* add a new file menu element: Reload
  - this should close everything opened and re-open them again.  
* add toolbar icon for the above. 
* add keyboard short cut F5
* add a popup menu to the model
* close all open files after saving their paths in a temp file 
* reload them again.

Notes:

 - when opening the main application, two text files are created 
   - OpenSimQtLog_DateTime.txt:  anything happened in the application should be logged in this file. 
      vsCommand: openmodel path 
      - It should also direct the outputto the messages window. 
   - OpenSim.vs: 
       - the first line is the date and time      
       - contains only the opened components (for now the model paths).

**Comment by idhamari** [comment]
Notice that all IO and critical code should be placed in error handling block that produces reasonable error in the application output and the application log.

**Comment by yasseerr** [comment]
HI!
Check this milestone in the latest master commit
the pop up is added but do you want to implement the functions of the popup on this milestone?

**Comment by idhamari** [comment]
Well done!

> the pop up is added but do you want to implement the functions of the popup on this milestone?

Is it complicated? I thought you just call the reload function.

I will test the code and give feedback if need.

**Comment by idhamari** [comment]
Just tested it, everything works. If calling the reload function from the popup menu is complicated, you may ignore it for now and close the issue.

**Comment by yasseerr** [comment]
> call the reload function
it is all the functions like(add Prob,Add Marker,Display, Toggle Parent Frame ...)it is not complicated but it require the work from the Visualizer functions Milestone like linking the visualizer and Navigator  and Navigator element popup menus ...

- For the reload function on the popup menu you want to reload just one Model from the model Menu?

**Comment by idhamari** [comment]
Ok, I understand what is the problem now. The reload function should reload only one object, when it is called from the menu or F5, it should reload everything,  

Another approach is  something like this:
                     
                    reload( ....,std::string object_name ){
                    try{
                    if object_name is in the navigator tree:
                       reload this object 
                    } else{
                      reload everything
                    }
                   }

**Comment by yasseerr** [comment]
i did not get it. 
The Current Reload Action reload everything when it called from the file that you described OpenSim.vs
For the New Reload Function on the popup menu you want it to reload just the Selected Model ?
Notice that all the model  are present in the Navigator Tree

**Comment by idhamari** [comment]
It ok, you may ignore this for now. This issue is now closed.
