### ISSUE TITLE
 MS0106: save functions: scene, model, element.

### ISSUE THREAD

**Issue by idhamari** [VisSimKoblenz/opensimQt#6]
*  Save model: save changes in current models. 
* Save model as: dialog where to save the model 
* Save All:
   - save the current model. 
   - a dialog where to save the scene.

**Comment by idhamari** [comment]
@yasseerr 

I just pushed a few modifications, please integrate them in your new code:

* adding target variable to cmake so no need to write the application name many times. Also the application name is the repository name.
*  adding an option to download the models to cmake. For now it is false by default. 
*  adding additional Geometry path, this should not affect the current one.  
*  adding few folders to the ignore list e.g. vsWorkSpace, as this will increase the size of the repository every time we push. 

Note: when you create a new branch, please consider the repository size and use only the source code files.

**Comment by yasseerr** [comment]
@idhamari  
Hi, I just integrated the changes with the tasks in this milestone
you can check if there is some leftovers in this commit https://github.com/VisSimKoblenz/opensimQt/commit/e9a87b7bc7dbaa1f21862fddbc5a3b57056862b0

**Comment by idhamari** [comment]
Well done! 

I will close this task for now, if there is something missing I will add a comment here. Please process to the next task.

Please note that I added the next milestone's tasks to make things are more clear for you. The second milestone has only 3 tasks, probably only one of them is challenging. The third milestone is straightforward.
