### ISSUE TITLE
MS0107: close functions: scene, model, element.

### ISSUE THREAD

**Issue by idhamari** [VisSimKoblenz/opensimQt#7]
Adding close functions to the main menu and a popup menu for file elements in the navigator. 

* [ ]  all file menu functions should be implmented at this point except two elements: load motion and preview experimental data.  
* [ ]  close model should be implemented in model popup menu as well. 
   - the model will be removed from the navigator and the visualizer.

**Comment by idhamari** [comment]
Creating the Windows release installer that contains:

* [ ] opensim-core installation.
* [ ] including vsWorkSpace with all models and geometry ..etc.
* [ ] including all VTK, Qt and other used libraries.

**Comment by yasseerr** [comment]
@idhamari 
check the last commit on the master branch for the closing part to see if something is missing
and for the installer GitHub does not allow file larger than 100MB so i could not push the installer
here is the link for the installer and a video showing it's execution on an empty VM
Installer: https://drive.google.com/open?id=1FLXNrVXiAj9LLkZmPrjxWZvjHoOrju4L
Video: https://drive.google.com/open?id=1pIAUMzEQbjyuh67YRyFRlr3XN8wkpu0_

**Comment by idhamari** [comment]
@yasseerr 

Thanks for the feedback! 

> check the last commit on the master branch

The last commit is from 4 days ago, is this correct one?.

> for the installer GitHub does not allow file larger than 100MB

I will put it somewhere else and links to Github. Is it possible to create this installer via a shell script?
 
 >   a video showing it's execution on an empty VM

the link does not work.

**Comment by idhamari** [comment]
@yasseerr 

> check the last commit on the master branch

I just built and test the model. I have a few comments: 

- It seems Linux geometry path is gone, did you integrate your work to the master or overwrite it? 
- The model popup menu: close function does not work.
- The file menu close: closes the first model in the navigator, not the selected one.
 - During the application exist, make a copy of the log and the scene files with a time stamp one can refer to them when needed. 
I think everything else works well. I like how the messages work.

**Comment by yasseerr** [comment]
> the last commit 
- yes it's the one from 4 days ago as the installer is separate from the master branch
> the demonstration video 
- this new link should work
[link](https://drive.google.com/open?id=1pIAUMzEQbjyuh67YRyFRlr3XN8wkpu0_)
> linux path geometries
- when i merged with master i set the geometries to be loaded from the workplace but if i deleted some linux parameters tell me so i can keep it when merging
- for the popup menu i intended to add it in the next milestone as it's groupe all functions in the popup menu the linking , however i will try to add it now and investigate the menu close the first not the selected(Current)
- for the exit functionalities you want the timestamp inside the file or in the name of the file

for the installer >
i used Qt Installer framework 
- basicly copy the opensimQt.exe to a clean folder
- use windeployqt.exe  forlder or linuxdeployqt command to  gather the dlls needed for Qt
- then create a package  for each module Qt,Vtk,OpenSim,Simbody by coping thr installation folder to the package and filling package.xml for each one
 - create create the config.xml in the config  forlder
 - then run binarycreator.exe(in the installer framwork ) on that folder to generate the installer
 - i will push the structure of the installer later

**Comment by idhamari** [comment]
Well done!

> for the exit functionalities you want the timestamp inside the file or in the name of the file

Just the file name. The idea is to have a backup of the file as when you run the applicaton again it rewrites the current one.

> i used Qt Installer framework

This should be automated. I think qt has a scripting language to do such stuff. Anyway, if you can not do it, I will do it. 

Please address the issues above, merge the updates then close this issue.

**Comment by yasseerr** [comment]
Hi again !
for the close first model problem i could not simulate it as the button close the current model,
and for me it's works(this exemple show that its close the second) can you give me more details for the problem
![2020-03-28_14-18-58](https://user-images.githubusercontent.com/37770658/77823954-3405fb00-70ff-11ea-9722-a739bc531ad0.gif)

**Comment by idhamari** [comment]
Thanks for the feedback. 
> for the close first model problem i could not simulate it as the button close the current model,

I can not reproduce the problem, so please ignore it for now.

**Comment by yasseerr** [comment]
the previous issues above have been solved
you can find the logs and the scenes in the History folder when closing
and the close button on the popup function has been added
